services:
  - type: web
    name: ai-resume-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

  - type: worker
    name: ai-resume-celery
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_app.celery worker --loglevel=info --pool=solo
